### ISSUE TITLE
hard-coded password for all uses presents security risk.

### ISSUE THREAD

**Issue by danmarsden** [dravek/moodle-tool_powerusers#2]
I'm a little uncomfortable with this line:
https://github.com/dravek/moodle-tool_powerusers/blob/master/classes/generator.php#L107

I think by default it should randomly assign a different password for each user (or even better - not set a password at all.)

basically this would allow someone to go looking for sites that have installed your plugin then try to login with the generic password, giving them authenticated access to the site.

**Comment by dravek** [comment]
Hi @danmarsden , thanks for your review! I fixed this issue and the other 2 in this pull request: https://github.com/dravek/moodle-tool_powerusers/pull/5/files
I created this plugin one day during our WP project week and because it was mainly focused on developers I thought having the password always set was the quick way to go, but you are right and I have fixed it as you requested. Now by default, it will generate a random password but you also have the choice to leave it blank or add your own.
I hope everything is fine now! Cheers!
